/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Models/Characters/Perci/Jump.glb -o src/components/Jump.jsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'animation_0' | 'animation_1' | 'animation_2' | 'animation_3' | 'animation_4' | 'animation_5' | 'animation_6' | 'animation_7' | 'animation_8' | 'animation_9' | 'animation_10' | 'animation_11' | 'animation_12' | 'animation_13' | 'animation_14' | 'animation_15' | 'animation_16' | 'animation_17' | 'animation_18' | 'animation_19' | 'animation_20' | 'animation_21' | 'animation_22' | 'animation_23' | 'animation_24' | 'animation_25' | 'animation_26' | 'animation_27' | 'animation_28' | 'animation_29' | 'animation_30' | 'animation_31' | 'animation_32' | 'animation_33'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    texture_pbr_v128: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
    mixamorigSpine: THREE.Bone
    mixamorigNeck: THREE.Bone
    mixamorigLeftShoulder: THREE.Bone
    mixamorigLeftArm: THREE.Bone
    mixamorigLeftForeArm: THREE.Bone
    mixamorigLeftHand: THREE.Bone
    mixamorigLeftHandThumb1: THREE.Bone
    mixamorigLeftHandThumb2: THREE.Bone
    mixamorigLeftHandThumb3: THREE.Bone
    mixamorigLeftHandIndex1: THREE.Bone
    mixamorigLeftHandIndex2: THREE.Bone
    mixamorigLeftHandIndex3: THREE.Bone
    mixamorigRightShoulder: THREE.Bone
    mixamorigRightArm: THREE.Bone
    mixamorigRightForeArm: THREE.Bone
    mixamorigRightHand: THREE.Bone
    mixamorigRightHandThumb1: THREE.Bone
    mixamorigRightHandThumb2: THREE.Bone
    mixamorigRightHandThumb3: THREE.Bone
    mixamorigRightHandIndex1: THREE.Bone
    mixamorigRightHandIndex2: THREE.Bone
    mixamorigRightHandIndex3: THREE.Bone
    mixamorigLeftUpLeg: THREE.Bone
    mixamorigLeftLeg: THREE.Bone
    mixamorigLeftFoot: THREE.Bone
    mixamorigLeftToeBase: THREE.Bone
    mixamorigRightUpLeg: THREE.Bone
    mixamorigRightLeg: THREE.Bone
    mixamorigRightFoot: THREE.Bone
    mixamorigRightToeBase: THREE.Bone
  }
  materials: {
    Materialmat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { scene, animations } = useGLTF('/Jump.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="RootNode">
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="texture_pbr_v128" geometry={nodes.texture_pbr_v128.geometry} material={materials.Materialmat} skeleton={nodes.texture_pbr_v128.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Jump.glb')
